[build]
  # Build when either content.json OR products.json changes
  # git diff --quiet returns 0 if no changes, 1 if changes exist
  # We check both files and build if either has changed
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- public/content.json public/products.json"

# Optional: Set Node version
[build.environment]
  NODE_VERSION = "18"