[build]
  # Build ONLY when content.json changes
  # Returns 1 (build) if content.json changed, 0 (ignore) if it didn't
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- public/content.json && echo 'No content.json changes, skipping build' || false"

# Optional: Set Node version
[build.environment]
  NODE_VERSION = "18"