[build]
  # ONLY build when content.json OR products.json changes
  # Returns exit 0 (skip build) if these files haven't changed
  # Returns exit 1 (do build) if either file has changed
  # This prevents image uploads from triggering deployments
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- public/content.json public/products.json"

# Optional: Set Node version
[build.environment]
  NODE_VERSION = "18"